'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class hrM08_NhanSuCongTy

    '''<summary>
    '''cbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnRefesh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefesh As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''gv_NhanSu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_NhanSu As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''DetailsView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailsView1 As Global.System.Web.UI.WebControls.DetailsView

    '''<summary>
    '''gv_LienHeKhanCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_LienHeKhanCap As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_BangCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_BangCap As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_ChungChi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_ChungChi As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_KyNang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_KyNang As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_CongTac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_CongTac As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_ChamCong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_ChamCong As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_PhepNam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_PhepNam As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_Luong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Luong As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_DieuChinhLuong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_DieuChinhLuong As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_HopDongLaoDong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_HopDongLaoDong As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_DaoTao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_DaoTao As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_ThangTien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_ThangTien As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_Thuong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Thuong As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_KyLuat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_KyLuat As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gv_KhamSucKhoe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_KhamSucKhoe As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource01_NhanSu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource01_NhanSu As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource01a_ChiTietNhanSu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource01a_ChiTietNhanSu As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource02_LienHeKhanCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource02_LienHeKhanCap As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource03_BangCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource03_BangCap As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource04_ChungChi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource04_ChungChi As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource05_KyNang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource05_KyNang As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource06_CongTac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource06_CongTac As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource07_ChamCong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource07_ChamCong As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource08_PhepNam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource08_PhepNam As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource09_Luong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource09_Luong As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource10_DieuChinhLuong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource10_DieuChinhLuong As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource11_HopDongLaoDong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource11_HopDongLaoDong As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource12_DaoTao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource12_DaoTao As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource13_ThangTien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource13_ThangTien As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource14_Thuong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource14_Thuong As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource15_KyLuat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource15_KyLuat As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource16_SucKhoe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource16_SucKhoe As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''TabName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabName As Global.System.Web.UI.WebControls.HiddenField
End Class
