'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class hrU00_NhanSu
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAdd As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtMaNhanVien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaNhanVien As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHoLot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoLot As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgaySinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgaySinh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgaySinh_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgaySinh_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtNoiSinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoiSinh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNguyenQuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNguyenQuan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbGioiTinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbGioiTinh As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbTinhTrangHonNhan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTinhTrangHonNhan As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtSoCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoCon As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSoCMND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoCMND As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayCap As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayCap_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayCap_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtNoiCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoiCap As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtThuongTru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtThuongTru As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTamTru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTamTru As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChucVu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChucVu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtThongBaoTrungTuyen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtThongBaoTrungTuyen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtQuyetDinhTuyenDung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuyetDinhTuyenDung As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHoSo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoSo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayVaoLamViec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayVaoLamViec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayVaoLamViec_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayVaoLamViec_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtNgayKetThucThuViec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayKetThucThuViec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayKetThucThuViec_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayKetThucThuViec_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtNgayKyHopDongLaoDong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayKyHopDongLaoDong As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayKyHopDongLaoDong_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayKyHopDongLaoDong_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtDienThoai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDienThoai As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDiDong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiDong As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmailCaNhan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailCaNhan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFacebook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacebook As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSoBHXH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoBHXH As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMaSoThue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaSoThue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSoTaiKhoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoTaiKhoan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHinhAnh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHinhAnh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbQuocTich control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbQuocTich As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbDanToc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDanToc As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbTonGiao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTonGiao As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbBanNganh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbBanNganh As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbTrinhDoHocVan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTrinhDoHocVan As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbTinhTrang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTinhTrang As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNgayNghi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayNghi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNgayNghi_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayNghi_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtMatKhau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMatKhau As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGhiChu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGhiChu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRecord As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtMaNhanVien1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaNhanVien1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHoLot1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoLot1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTen1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTen1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgaySinh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgaySinh1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgaySinh1_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgaySinh1_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtNoiSinh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoiSinh1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNguyenQuan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNguyenQuan1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbGioiTinh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbGioiTinh1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbTinhTrangHonNhan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTinhTrangHonNhan1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtSoCon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoCon1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSoCMND1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoCMND1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayCap1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayCap1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayCap1_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayCap1_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtNoiCap1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoiCap1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtThuongTru1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtThuongTru1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTamTru1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTamTru1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChucVu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChucVu1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtThongBaoTrungTuyen1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtThongBaoTrungTuyen1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtQuyetDinhTuyenDung1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuyetDinhTuyenDung1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHoSo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoSo1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayVaoLamViec1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayVaoLamViec1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayVaoLamViec1_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayVaoLamViec1_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtNgayKetThucThuViec1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayKetThucThuViec1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayKetThucThuViec1_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayKetThucThuViec1_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtNgayKyHopDongLaoDong1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayKyHopDongLaoDong1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNgayKyHopDongLaoDong1_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayKyHopDongLaoDong1_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtDienThoai1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDienThoai1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDiDong1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiDong1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmailCaNhan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailCaNhan1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFacebook1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacebook1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSoBHXH1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoBHXH1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMaSoThue1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaSoThue1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSoTaiKhoan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoTaiKhoan1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHinhAnh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHinhAnh1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbQuocTich1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbQuocTich1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbDanToc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDanToc1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbTonGiao1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTonGiao1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbBanNganh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbBanNganh1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbTrinhDoHocVan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTrinhDoHocVan1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbTinhTrang1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTinhTrang1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNgayNghi1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayNghi1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNgayNghi1_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgayNghi1_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtMatKhau1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMatKhau1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGhiChu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGhiChu1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''upDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hfCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblMaNhanVien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaNhanVien As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''HyperLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink8 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink9 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink10 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink11 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink12 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink13 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink14 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLink15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink15 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SqlDataSource1_NhanSu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1_NhanSu As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSource3_QuocTich control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource3_QuocTich As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSource4_DanToc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource4_DanToc As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSource5_TonGiao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource5_TonGiao As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSource6_TrinhDoHocVan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource6_TrinhDoHocVan As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSource7_ChiNhanh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource7_ChiNhanh As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSource8_BoPhanLamViec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource8_BoPhanLamViec As Global.System.Web.UI.WebControls.SqlDataSource
End Class
